<?php

namespace App\Services;

use App\Models\Article;
use App\Support\Locales;
use Imagick;
use ImagickDraw;
use ImagickPixel;

/**
 * Renders the 1200x630 Open Graph card for an article into public/assets/og/.
 * Output is a derived artifact (rebuildable from the DB, which is itself
 * rebuildable from the content repo), so the whole tree is gitignored and
 * regenerated by hondabase:reindex.
 */
class OgImageGenerator
{
    private const WIDTH = 1200;

    private const HEIGHT = 630;

    /** Colors mirror the @theme tokens in resources/css/app.css. */
    private const BG = '#0a0a0b';

    private const HEAD = '#f4f4f5';

    private const DIM = '#a1a1aa';

    private const RED = '#e10600';

    private const AMBER = '#fbbf24';

    private const BORDER = '#27272a';

    /** Public path (relative to public/) of an article's card, generated or not. */
    public static function relativePath(Article $article): string
    {
        return self::pathFor($article->type, $article->category, $article->slug, $article->locale);
    }

    public static function pathFor(string $type, string $category, string $slug, string $locale): string
    {
        $prefix = Locales::isDefault($locale) ? '' : $locale.'/';

        return 'assets/og/'.$prefix.$type.'/'.$category.'/'.$slug.'.png';
    }

    /**
     * Generate the card unless a fresh one already exists (mtime >= the
     * article's updated_at). Returns the relative path of the PNG.
     */
    public function generate(Article $article, bool $force = false): string
    {
        $rel = self::relativePath($article);
        $abs = public_path($rel);

        if (! $force && is_file($abs) && $article->updated_at && filemtime($abs) >= $article->updated_at->getTimestamp()) {
            return $rel;
        }

        if (! is_dir(dirname($abs))) {
            mkdir(dirname($abs), 0775, true);
        }

        $img = new Imagick;
        $img->newImage(self::WIDTH, self::HEIGHT, new ImagickPixel(self::BG));
        $img->setImageFormat('png');

        // Red top rule + faint bottom border, echoing the site chrome.
        $draw = new ImagickDraw;
        $draw->setFillColor(new ImagickPixel(self::RED));
        $draw->rectangle(0, 0, self::WIDTH, 10);
        $draw->setFillColor(new ImagickPixel(self::BORDER));
        $draw->rectangle(0, self::HEIGHT - 2, self::WIDTH, self::HEIGHT);
        $img->drawImage($draw);

        // Wordmark: HONDA in white, BASE in red, like the header brand.
        $display = resource_path('fonts/og/ChakraPetch-Bold.ttf');
        $mono = resource_path('fonts/og/IBMPlexMono-Regular.ttf');
        $wordmark = new ImagickDraw;
        $wordmark->setFont($display);
        $wordmark->setFontSize(38);
        $wordmark->setFillColor(new ImagickPixel(self::HEAD));
        $img->annotateImage($wordmark, 70, 110, 0, 'HONDA');
        $metrics = $img->queryFontMetrics($wordmark, 'HONDA');
        $wordmark->setFillColor(new ImagickPixel(self::RED));
        $img->annotateImage($wordmark, 70 + $metrics['textWidth'], 110, 0, 'BASE');

        // Breadcrumb line: TYPE / CATEGORY (uppercased, mono, amber).
        $crumb = strtoupper($article->type.' / '.str_replace('/', ' / ', $article->category));
        if (! Locales::isDefault($article->locale)) {
            $crumb .= '   ['.strtoupper($article->locale).']';
        }
        $crumbDraw = new ImagickDraw;
        $crumbDraw->setFont($mono);
        $crumbDraw->setFontSize(26);
        $crumbDraw->setFillColor(new ImagickPixel(self::AMBER));
        $img->annotateImage($crumbDraw, 70, 230, 0, $this->truncateToWidth($img, $crumbDraw, $crumb, 1060));

        // Title: up to 3 wrapped lines, shrinking before it ellipsizes.
        $titleDraw = new ImagickDraw;
        $titleDraw->setFont($display);
        $titleDraw->setFillColor(new ImagickPixel(self::HEAD));
        foreach ([66, 58, 50] as $size) {
            $titleDraw->setFontSize($size);
            $lines = $this->wrap($img, $titleDraw, $article->title, 1060, 3);
            if ($lines['fits'] || $size === 50) {
                $y = 320;
                foreach ($lines['lines'] as $line) {
                    $img->annotateImage($titleDraw, 70, $y, 0, $line);
                    $y += (int) round($size * 1.25);
                }
                break;
            }
        }

        // Footer: the site, quietly.
        $footer = new ImagickDraw;
        $footer->setFont($mono);
        $footer->setFontSize(22);
        $footer->setFillColor(new ImagickPixel(self::DIM));
        $img->annotateImage($footer, 70, 575, 0, 'www.hondabase.com');

        $img->writeImage($abs);
        $img->destroy();
        @chmod($abs, 0664);

        return $rel;
    }

    /** Remove the generated card for an article (used when it is hidden or deleted). */
    public function remove(Article $article): void
    {
        $abs = public_path(self::relativePath($article));
        if (is_file($abs)) {
            unlink($abs);
        }
    }

    /** @return array{lines: string[], fits: bool} Greedy word wrap capped at $maxLines. */
    private function wrap(Imagick $img, ImagickDraw $draw, string $text, int $maxWidth, int $maxLines): array
    {
        $words = preg_split('/\s+/u', trim($text)) ?: [];
        $lines = [];
        $current = '';
        foreach ($words as $word) {
            $candidate = $current === '' ? $word : $current.' '.$word;
            if ($img->queryFontMetrics($draw, $candidate)['textWidth'] <= $maxWidth) {
                $current = $candidate;

                continue;
            }
            $lines[] = $current === '' ? $word : $current;
            $current = $current === '' ? '' : $word;
            if (count($lines) === $maxLines) {
                return ['lines' => $this->ellipsize($img, $draw, $lines, $current, $maxWidth), 'fits' => false];
            }
        }
        if ($current !== '') {
            $lines[] = $current;
        }

        return ['lines' => $lines, 'fits' => true];
    }

    /** @param string[] $lines */
    private function ellipsize(Imagick $img, ImagickDraw $draw, array $lines, string $rest, int $maxWidth): array
    {
        $last = end($lines);
        if ($rest !== '') {
            $last .= '...';
            while ($last !== '...' && $img->queryFontMetrics($draw, $last)['textWidth'] > $maxWidth) {
                $last = rtrim(mb_substr($last, 0, -4)).'...';
            }
            $lines[count($lines) - 1] = $last;
        }

        return $lines;
    }

    private function truncateToWidth(Imagick $img, ImagickDraw $draw, string $text, int $maxWidth): string
    {
        while ($text !== '' && $img->queryFontMetrics($draw, $text)['textWidth'] > $maxWidth) {
            $text = rtrim(mb_substr($text, 0, -4)).'...';
        }

        return $text;
    }
}
